### ISSUE TITLE
Bug with geckodriver

### ISSUE THREAD

**Issue by roaffix** [JaxSulav/Automated-facebook-events-scraping#1]
Hi, I faced the following bug
```
Working in background..........................
This may take some time depending on the internet consistency
Traceback (most recent call last):
  File "eventScrape.py", line 209, in <module>
    links_gather()
  File "eventScrape.py", line 30, in links_gather
    browser = webdriver.Firefox(options=options)
  File "/Users/user/.venvs/mattenot/lib/python3.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 164, in __init__
    self.service.start()
  File "/Users/user/.venvs/mattenot/lib/python3.7/site-packages/selenium/webdriver/common/service.py", line 76, in start
    stdin=PIPE)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 756, in __init__
    restore_signals, start_new_session)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 1499, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
NotADirectoryError: [Errno 20] Not a directory: 'geckodriver'
```

I just added geckodriver to path with `PATH = $PATH:./geckodriver`.
And started script `python eventScrape.py --year=2018 --month=1`.

Any suggestions?

**Comment by JaxSulav** [comment]
Hello, sorry for the late reply. How about you copy the geckodriver file to the project's directory? There is already a path to geckodriver in script.

**Comment by roaffix** [comment]
> Hello, sorry for the late reply. How about you copy the geckodriver file to the project's directory? There is already a path to geckodriver in script.

It doesn't work. Says that geckodriver is not in path

**Comment by JaxSulav** [comment]
Do yoy have geckodriver in your usr/bin ? If not, put it there. It should work.

**Comment by JaxSulav** [comment]
> It doesn't work. Says that geckodriver is not in path

I tested it in another device, the same error came up which I solved by putting geckodriver in usr/bin. Hope this helps. Also, I have updated readme.md for instructions.

**Comment by roaffix** [comment]
> I solved by putting geckodriver in usr/bin.

Did you put just unzipped folder ?

**Comment by JaxSulav** [comment]
> Did you put just unzipped folder ?

I put unzipped file, the geckodriver file to the project folder and to usr/bin/ :)
Also, make sure it is the geckodriver for your system, choose from [ https://github.com/mozilla/geckodriver/releases](url)

**Comment by roaffix** [comment]
MB, I tried to put the source code in there 🤦‍♂️ 

But in the result the output folder is empty and you get banned on your fake account (Whoops)

**Comment by JaxSulav** [comment]
LOL. I knew one day it would get banned. Create a fake account and pass it in auto_login function. I assure you that output folder won't be empty. Have tried it in many devices.
